package entity

/*
structure for user containing friends, liked songs and user id
// friends and likedsong should contain an array of strings and userID should be a string
//Friends is a list of all of the friends of a user on the platform
//LikedSong is a list of all of the songs that a user has liked on the platform using the Tinder UI (swiping right)
//UserID is the unique identifier of a user that is generated by the platform
//GroupAdmin is a map of all of the groups that a user is an admin of and a boolean value that is true if the user is an admin of the group
*/
type User struct {
	Friends    []string        `json:"friends"`
	LikedSong  []string        `json:"likedSong"`
	UserID     string          `json:"userID"`
	GroupAdmin map[string]bool `json:"groupAdmin"` // key is group id, admin status
}
